version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
            - MYSQL_DATABASE=sample
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=password
            - TZ=Japan
  web:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
